<template>
  <nav class="breadcrumb is-centered box no-bottom" aria-label="breadcrumbs">
    <ul>
      <!-- TODO make this dynamic possibly read from $route with an if statement for devices/1 etc -->
      <!-- This should be structured as follows home/customer/facility/device -->
      <li v-for="location in breadcrumbArray" :key="location.title">
        <router-link :to="location.link">{{ location.title }}</router-link>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: 'breadcrumb',
  data() {
    return {
      breadcrumbArray: []
    }
  },
  watch: {
    $route (to, from) {
      this.determineBreadcrumb(to)
    }
  },
  created() {
    this.determineBreadcrumb()
  },
  methods: {
    /* Logic to determine the breadcrumb to display
     * @param {string} newRoute the $route generated by vue
     * @returns {array}
     */
    determineBreadcrumb(newRoute = null) {
      var self = this

      if(newRoute) {
        var routeName = newRoute.name
        console.log(routeName)

        self.breadcrumbSwitch(routeName)
      } else {
        var routeName = self.$route.name
        console.log(routeName)

        self.breadcrumbSwitch(routeName)
      }
    },
    breadcrumbSwitch(routeName) {
      var self = this

      switch (routeName) {
          case 'device':
            break
          case 'customer':
            break
          case 'facility':
            self.breadcrumbArray = [{
              title: 'Home',
              link: '/'
            }]

            break
          default:
            /* Return just home */
            self.breadcrumbArray = [{
              title: 'Home',
              link: '/'
            }]
      }
    }
  }
}
</script>

<style scoped>
.no-bottom {
  margin-bottom: 0;
}
</style>
